name: Build FBNeo Plus for iOS
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Package
        run: |
          # 1. 直接进入核心源码目录并编译
          # 我们使用 -C 参数直接指定目录，这样更稳
          echo "Starting build..."
          make -C src/burner/libretro -f Makefile.libretro platform=ios-arm64 -j$(sysctl -n hw.ncpu)
          
          # 2. 将生成的核心重命名并移动到根目录
          # 刚才日志确认了路径就在 src/burner/libretro
          mv src/burner/libretro/fbneo_libretro_ios.dylib ./fbneo_plus
          
          # 3. 创建 Info 文件
          cat <<EOF > fbneo_plus.info
          display_name = "Arcade (FBNeo Plus - Hack Edition)"
          authors = "Team FBNeo & lrf739146825"
          supported_extensions = "zip|7z|dat|neogeo"
          corename = "FBNeo Plus"
          manufacturer = "Various"
          categories = "Emulator"
          systemname = "Arcade (various)"
          database = "FBNeo - Arcade Games"
          license = "Non-commercial"
          permissions = ""
          display_version = "v1.0.0.3"
          supports_no_game = "false"
          EOF

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FBNeo_Plus_iOS
          path: |
            fbneo_plus
            fbneo_plus.info
